import { Transaction } from "@mysten/sui/transactions";
import { compileMove } from "../compiler/moveCompiler";
import { prepareArtifactManifestForTarget } from "../compiler/emitter";
import type {
  DeploymentTarget,
  DeployGradeCompileResult,
  GeneratedContractArtifact,
  PackageReferenceBundle,
} from "../compiler/types";

export interface RemotePublishRequest {
  readonly artifact?: GeneratedContractArtifact;
  readonly compileResult?: DeployGradeCompileResult;
  readonly ownerAddress: string;
  readonly onSubmitting?: () => void;
  readonly target: DeploymentTarget;
  readonly references: PackageReferenceBundle;
  readonly execute: (transaction: Transaction, request?: RemotePublishExecutionRequest) => Promise<{ digest: string }>;
  readonly signal?: AbortSignal;
}

export interface RemotePublishExecutionRequest {
  readonly onSubmitting?: () => void;
  readonly signal?: AbortSignal;
}

export interface RemotePublishResult {
  readonly packageId?: string;
  readonly transactionDigest?: string;
  readonly sourceVersionTag?: string;
  readonly builderToolchainVersion?: string;
}

const TESTNET_CHAIN_ID = "4c78adac";
const REMOTE_WORLD_DEPENDENCY_LINKING_ERROR = [
  "Remote deployment cannot resolve the published world dependency in the browser Move compiler.",
  "Published.toml only applies to the root package in the current toolchain, so this deploy path cannot link the live world package yet.",
].join(" ");

function extractMoveEdition(moveToml: string): string {
  const match = moveToml.match(/edition\s*=\s*"([^"]+)"/);
  return match?.[1] ?? "2024.beta";
}

function createPublishedWorldDependencyManifest(references: PackageReferenceBundle): string {
  return [
    "# Generated by Frontier Flow for remote deployment compilation",
    "[published.testnet]",
    `chain-id = "${TESTNET_CHAIN_ID}"`,
    `published-at = "${references.worldPackageId}"`,
    `original-id = "${references.originalWorldPackageId}"`,
    "version = 1",
    `toolchain-version = "${references.toolchainVersion}"`,
    'build-config = { flavor = "sui", edition = "2024" }',
    'upgrade-capability = "0x0"',
    "",
  ].join("\n");
}

function createRemoteCompilationMoveToml(artifact: GeneratedContractArtifact): string {
  const edition = extractMoveEdition(artifact.moveToml);

  return [
    "[package]",
    `name = "${artifact.moduleName}"`,
    `edition = "${edition}"`,
    "",
    "[addresses]",
    'builder_extensions = "0x0"',
    "",
    "[dependencies]",
    'world = { local = "deps/world" }',
    "",
  ].join("\n");
}

function createRemoteCompilationArtifact(
  artifact: GeneratedContractArtifact,
  references: PackageReferenceBundle,
): GeneratedContractArtifact {
  const sourceFiles = artifact.sourceFiles ?? [{ path: artifact.sourceFilePath, content: artifact.moveSource }];
  const transformedSourceFiles = sourceFiles.filter((file) => file.path !== "deps/world/Published.toml");

  transformedSourceFiles.push({
    path: "deps/world/Published.toml",
    content: createPublishedWorldDependencyManifest(references),
  });

  return {
    ...artifact,
    moveToml: createRemoteCompilationMoveToml(artifact),
    sourceFiles: transformedSourceFiles,
    dependencies: [],
    bytecodeModules: [],
  };
}

async function compileArtifactForRemotePublish(
  artifact: GeneratedContractArtifact,
  references: PackageReferenceBundle,
): Promise<GeneratedContractArtifact> {
  const compileResult = await compileMove(createRemoteCompilationArtifact(artifact, references));

  if (!compileResult.success || compileResult.artifact === null) {
    const diagnosticMessage = compileResult.errors?.[0]?.userMessage
      ?? compileResult.errors?.[0]?.rawMessage
      ?? "Remote deployment compilation failed.";

    if (/address with no value/i.test(diagnosticMessage)) {
      throw new Error(REMOTE_WORLD_DEPENDENCY_LINKING_ERROR);
    }

    throw new Error(diagnosticMessage);
  }

  return compileResult.artifact;
}

function requireOwnerAddress(request: RemotePublishRequest): void {
  if (request.ownerAddress.length === 0) {
    throw new Error(`A connected wallet address is required before deploying to ${request.target.label}.`);
  }
}

function resolveCompileInputArtifact(request: RemotePublishRequest): GeneratedContractArtifact {
  if (request.artifact !== undefined) {
    return request.artifact;
  }

  throw new Error("A compiled artifact is required for remote publishing.");
}

async function resolvePublishModules(
  request: RemotePublishRequest,
): Promise<{ readonly compileResult?: DeployGradeCompileResult; readonly compiledArtifact: GeneratedContractArtifact | null }> {
  if (request.compileResult !== undefined) {
    return { compileResult: request.compileResult, compiledArtifact: null };
  }

  return {
    compileResult: undefined,
    compiledArtifact: await compileArtifactForRemotePublish(resolveCompileInputArtifact(request), request.references),
  };
}

function normalizeRemotePublishDependencies(
  dependencies: readonly string[],
  references: PackageReferenceBundle,
): readonly string[] {
  const normalizedDependencies = dependencies.map((dependency) => {
    if (dependency === references.originalWorldPackageId) {
      return references.worldPackageId;
    }

    return dependency;
  });

  if (!normalizedDependencies.includes(references.worldPackageId)) {
    normalizedDependencies.push(references.worldPackageId);
  }

  return Array.from(new Set(normalizedDependencies));
}

function resolveRemoteDependencies(
  request: RemotePublishRequest,
  compileResult: DeployGradeCompileResult | undefined,
  compiledArtifact: GeneratedContractArtifact | null,
): readonly string[] {
  if (compileResult !== undefined) {
    return normalizeRemotePublishDependencies(compileResult.dependencies, request.references);
  }

  return normalizeRemotePublishDependencies(
    prepareArtifactManifestForTarget(
      compiledArtifact?.moduleName ?? request.artifact?.moduleName ?? "unknown-module",
      request.target.id,
      compiledArtifact?.dependencies ?? [],
    ).dependencies,
    request.references,
  );
}

function createPublishTransaction(
  modules: readonly Uint8Array[],
  dependencies: readonly string[],
  ownerAddress: string,
): Transaction {
  const transaction = new Transaction();
  const [upgradeCap] = transaction.publish({
    modules: modules.map((module) => Array.from(module)),
    dependencies: Array.from(dependencies),
  });
  transaction.transferObjects([upgradeCap], ownerAddress);
  return transaction;
}

/**
 * Publish a compiled artifact to a supported remote Sui target.
 */
export async function publishToRemoteTarget(request: RemotePublishRequest): Promise<RemotePublishResult> {
  requireOwnerAddress(request);

  const { compileResult, compiledArtifact } = await resolvePublishModules(request);
  const modules = compileResult?.modules ?? compiledArtifact?.bytecodeModules ?? [];
  const dependencies = resolveRemoteDependencies(request, compileResult, compiledArtifact);
  const transaction = createPublishTransaction(modules, dependencies, request.ownerAddress);

  const result = await request.execute(transaction, {
    onSubmitting: request.onSubmitting,
    signal: request.signal,
  });
  return {
    builderToolchainVersion: compileResult?.builderToolchainVersion,
    sourceVersionTag: compileResult?.sourceVersionTag,
    transactionDigest: result.digest,
  };
}