#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$repo_root"

if [[ ! -f package.json ]]; then
  echo "package.json not found in repo root"
  exit 1
fi

declare -a steps=(
  "typecheck|bun run typecheck"
  "build|bun run build"
  "lint|bun run lint"
  "unit-tests|bun run test:run"
  "playwright|bun run test:e2e"
)

declare -a failed=()
todo_file="verify-remediation-todo.md"

run_step() {
  local name="$1"
  local cmd="$2"

  echo
  echo "== Running $name =="
  if eval "$cmd"; then
    echo "[OK] $name"
  else
    echo "[FAIL] $name"
    failed+=("$name")
  fi
}

for step in "${steps[@]}"; do
  name="${step%%|*}"
  cmd="${step#*|}"
  run_step "$name" "$cmd"
done

if [[ ${#failed[@]} -eq 0 ]]; then
  echo
  echo "All verification checks passed."
  exit 0
fi

{
  echo "# Remediation TODOs"
  echo
  echo "Generated by .github/skills/verify-and-remediate.sh"
  echo
  for failure in "${failed[@]}"; do
    echo "- [ ] Investigate and fix: $failure"
  done
} > "$todo_file"

echo
echo "Checks failed: ${failed[*]}"
echo "Created $todo_file"
