$ErrorActionPreference = 'Stop'

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptRoot '../..')
Set-Location $repoRoot

if (-not (Test-Path 'package.json')) {
    Write-Error 'package.json not found in repo root'
}

$steps = @(
    @{ Name = 'typecheck'; Command = 'bun run typecheck' }
    @{ Name = 'build'; Command = 'bun run build' }
    @{ Name = 'lint'; Command = 'bun run lint' }
    @{ Name = 'unit-tests'; Command = 'bun run test:run' }
    @{ Name = 'playwright'; Command = 'bun run test:e2e' }
)

$failed = [System.Collections.Generic.List[string]]::new()
$todoFile = 'verify-remediation-todo.md'

foreach ($step in $steps) {
    Write-Host ''
    Write-Host "== Running $($step.Name) =="

    if ($IsWindows) {
        & cmd /c $step.Command
    }
    else {
        & /bin/sh -lc $step.Command
    }

    if ($LASTEXITCODE -eq 0) {
        Write-Host "[OK] $($step.Name)"
    }
    else {
        Write-Host "[FAIL] $($step.Name)"
        $failed.Add($step.Name)
    }
}

if ($failed.Count -eq 0) {
    Write-Host ''
    Write-Host 'All verification checks passed.'
    exit 0
}

$content = @(
    '# Remediation TODOs'
    ''
    'Generated by .github/skills/verify-and-remediate.ps1'
    ''
)

foreach ($failure in $failed) {
    $content += "- [ ] Investigate and fix: $failure"
}

Set-Content -Path $todoFile -Value $content

Write-Host ''
Write-Host "Checks failed: $($failed -join ', ')"
Write-Host "Created $todoFile"
